### ISSUE TITLE
Typing into text boxes sometimes causes OS-wide global actions (hotkeys?)

### ISSUE THREAD

**Issue by ghost** [stefankueng/grepWin#11]
Hello
Some characters are going outside of GrepWin and doing action in other, stealing focus, and doing actions which aren't usual for most utilities.

Right now when I type and press "o" the selected file below will be opened, yesterday when I was typing and had to press "o" it switched focus to Visual Studio 2017 Community and started typing there.

I did not had VS2017 open right now, I do have git bash open, opera, firefox, most of the programs are quite recent because this is a fresh (2 month) old Windows 10 installation.

**Comment by stefankueng** [comment]
I think that's not grepWin's fault. Such behavior usually comes from other tools that either register global hotkeys or hook into other processes. grepWin does neither of those things.

**Comment by severinkann** [comment]
Same here. When typing 'o' or 'O' it opens the selected file with standard application.

I think the problem was introduced with this change: 
https://github.com/stefankueng/grepWin/commit/db49acf44cd6363d694a05415ceb90b39088fa79

For other hotkeys there is a fix but for 'O' it is missing:
https://github.com/stefankueng/grepWin/commit/eb9b0047e2861805aafbd26375f7947bff0ebab9

**Comment by ghost** [comment]
I've seen it happen today again, it didn't happen all day, it happend when I had grepWin opened. This time I was typing somewhere else, and grepWin was probably behind another window, not minimized, I don't remember exactly, because I didn't follow up as I was busy with 3 different things at the same time, and it maximized another window ... now it makes perfect sense when I got back here.

It didn't happen while I was actually typing into any of the boxes, and yes the words I used did contain "o".

Now that I'm seening some patterns here, I'll be doing proper monitoring for this issue next time I use it, I forgot about the issue while I was using it today, I'll put it all on video if I get similar behavior again.

While I probably should have done more testing, for a few days, so I have a more stronger opinion as to who might be at the fault, I do have a pretty big history of Windows tweaking and general computer maintenance, I basically can see the slightest weirdness going on and I usually fix things manually in registry what most other people would be way too impatient and would reinstall the whole OS for, I'm not an average windows user, so wouldn't start an issue so lightly, but I'm not saying the experience makes me 100% correct in this case, but this is where the evidence points at this moment.

The behavior might be real, it may be something else causing it, or something else going through grepWin, so it may be that grepWin is just the spark, but we'll see.

**Comment by stefankueng** [comment]
While it is possible for applications to react to keys entered in other applications, that requires some very specific APIs to call. grepWin doesn't do that.
On itself, grepWin simply can not catch keys entered in other applications. Really, that's not possible.
An application only receives keyboard inputs if it has the focus, and ever since Windows Vista, the OS actually prevents applications from even accidentally stealing the focus.

So please yes, try to do more testing and maybe you can figure out the root of the problem.

**Comment by ghost** [comment]
Video Proof Cat1 Example 1: https://gfycat.com/SelfishVengefulHuemul
It's trying to open one of the files I had previously selected (not visible here) in grepWin results window.

It happens randomly on very specific occasion, I keept using it for 30 minutes until it happened, I was browsing throug the list previously, I forgot what I actually did the last time before typing, I may have switched other application windows, doing stuff on the PC normally, as you can see as soon as I switched focus and selected something in the GUI, it stopped affecting the OS.

Update1:
Video Proof Cat1 Example 2: https://gfycat.com/CavernousOblongJackal
Video Proof Cat1 Example 3: https://gfycat.com/UglySlipperyIndianskimmer

A little bit of poking did the trick and keeps being repeatable now, seems like it's extension specific, extensionless files and maybe files with "o" or something inside the extension don't seem to cause it, but everything else like `.js .txt .h .cmake` did.

This is category 1 - "o" opens up a file selected in results box while typing in another textbox.
I'll add more categories if I see them, like switching window focus, I haven't experienced ever since those two times so when I do I'll fill in, I suspect more such, so I'll separate them into categories.

**Comment by smelcher** [comment]
I am experiencing the same problem.  Here are the steps that reproduce the problem for me:

1. Run a search so that you get results in the "Search Results" window.
2. Click on one of the files
3. Click back in the the "File names match" field
4. Type the letter "o"

This will open the selected file.  In my case, it launches the file in Notepad++ because it is a test file.

Thanks for looking in to this!

**Comment by stefankueng** [comment]
please test version 1.8.0. it should be fixed but since I can't reproduce the problem, I can't be sure.

**Comment by severinkann** [comment]
Tested with 1.8.0: OK. Thanks a lot!

**Comment by stefankueng** [comment]
Thanks for testing.
Closing this issue now.

**Comment by smelcher** [comment]
It works! Thanks!
