### ISSUE TITLE
Display version difference

### ISSUE THREAD

**Issue by dmueller4** [stefankueng/grepWin#154]
Hi Stefan, 
I noticed a little difference in the version string of the application. I was checking the version via PowerShell to see if I need to update. 
in github Tag version : 2.0.1
in about grepWin: 2.0.1.882
in windows installed program: 2.0.882

Here are some screenshots of the version:
in the program
![image](https://user-images.githubusercontent.com/4864383/83902221-46825d80-a75c-11ea-9c50-6620c4f62ca7.png)
in windows installed apps
![image](https://user-images.githubusercontent.com/4864383/83902244-50a45c00-a75c-11ea-8b35-3b9c254565d9.png)
in PowerShell
![image](https://user-images.githubusercontent.com/4864383/83902350-86e1db80-a75c-11ea-974c-6b2acb8411ed.png)

**Comment by stefankueng** [comment]
the problem is that msi, while it actually has four numbers in it's version, doesn't respect the fourth number at all when doing updates/upgrades.
So to avoid problems with dev builds, I use the fourth number (the build number) as the third number in the msi.

for example, for msi the two versions
2.0.1.100
2.0.1.101
are the same and you can't update. msi ignores the fourth part.

that's why for the msi version, I skip the third number and use the build number as the third one. That way I can ensure that even dev builds always install/update properly.
