### ISSUE TITLE
GUI / Windows 7

### ISSUE THREAD

**Issue by Nighted** [stefankueng/grepWin#16]
I tried 1.8.0 and the preview you have looks like Windows 10...and that looks fine...still too big though.

I'm using it on Windows 7 and the GUI looks like it lived on mac & cheese for several months and now can't get out the door to go anywhere so it's smashing a hole through the wall with its face.

I'll use it on my Windows 10 laptop but I'll stick with 1.7.2 on my workstation because it's not hideous. :)

![a](https://user-images.githubusercontent.com/16041139/40791077-9629ec36-64c4-11e8-9b32-c42f65e096e3.png)
![b](https://user-images.githubusercontent.com/16041139/40791078-9671d514-64c4-11e8-9742-a0aa251cb4f0.png)

**Comment by jkyeung** [comment]
I agree that the latest version doesn't look good on Windows 7. I'm not sure if there's a better place to put the new date limits though. So maybe it has to be "too big". Aesthetically, the worst part of the new GUI for me is the buttons on the right. They look like they are slightly cut off due to the right border. But then if you try to widen the window (yes, to make it even more monstrously wide), the buttons stick to the border, and stay cut-off-looking. Surely fixing this is a simple matter of adding a little spacing.

**Comment by jkyeung** [comment]
Oh wait, I noticed something else that is even worse - the settings dialog:

![image](https://user-images.githubusercontent.com/4826859/44114968-a4434d20-9fda-11e8-8f0f-a70726ead68d.png)

What is going on at the bottom? It almost looks like some kind of weird new-style scroll bar.

**Comment by stefankueng** [comment]
@jkyeung : settings dialog fixed in bbb9ff770ad26a3875b08190cfe6049adf1e38dc

**Comment by ghost** [comment]
I've noticed wonky defaults as well, weird dates, or are those intended defaults ??? (regex search, only less than 2000kb, etc)

**Comment by stefankueng** [comment]
dwm isn't used anymore.
