### ISSUE TITLE
FeatureRequest - search files with specific Encoding

### ISSUE THREAD

**Issue by mlipok** [stefankueng/grepWin#197]
I need to find all my scirpt files which grepWin recognize as ANSI
and add to them this following line

# DO NOT REMOVE THIS LINE THIS IS TO AVOID PROBLEMS WITH ENCODING ąćęłńóśżźĄĆĘŁŃÓŚŻŹ

to be sure that grepWin will recognize them in the next time as UTF8NOBOM

I attach ZIP with 2 files:
TEST_1_WRONG.au3
TEST_2_GOOD.au3

In SciTE editor : 
https://www.autoitscript.com/site/autoit-script-editor/downloads/

I have them (both au3 files) recognized as UFT8 NO BOM

Thanks to grepWin I found that some other program recognized TEST_2_GOOD.au3 as ANSI 

I have found a workaround to put 
# DO NOT REMOVE THIS LINE THIS IS TO AVOID PROBLEMS WITH ENCODING ąćęłńóśżźĄĆĘŁŃÓŚŻŹ

of course using this SciTE instalation, and then all oter programs will recognize this file as UTF8 NO BOM.

[Encoding_Issue.zip](https://github.com/stefankueng/grepWin/files/5279880/Encoding_Issue.zip)

**Comment by stefankueng** [comment]
the test files you attached show that the one that's recognized as ANSI has no real text in it.
Since utf8 and ANSI are the same if no chars above the 127 mark are present, grepWin defaults to ANSI instead of utf8.
But it really doesn't matter, because in that case it makes absolutely no difference.

however, there's a checkbox "treat files as utf8" in grepWin if you prefer the default to be utf8.
