### ISSUE TITLE
The export result list is always opened and uses Notepad instead of the defined editor in the settings

### ISSUE THREAD

**Issue by f6fvy** [stefankueng/grepWin#205]
After a search, you can export results by using the arrow button located in the bottom right of the GrepWin window.

After entering a file name and setting or not various options in the file dialog, the export file is created, and it's automatically opened in Notepad.

1/ Unless I miss something, there is no setting to *not* open this file automatically. Would it be possible to add it ?

2/ A default editor path can be set in the settings dialog. Use this editor to open this file instead of Notepad.

**Comment by stefankueng** [comment]
- the file is opened in the default application for the file type, so if you specified the save-as filename as e.g. "export.txt" then the file is opened with the default app for text files. If you don't like notepad, then why do you have it as the default for that extension?
- using the editor specified in the settings is not a good idea for this use case, I think
- adding another option to just not open the file after exporting: won't do, because it's one click to close that application after exporting
