### ISSUE TITLE
Confusing specification of in/excluded directories/files

### ISSUE THREAD

**Issue by tobwz** [stefankueng/grepWin#231]
I am confused about how users have to specify directories and files.

A normal and intuitive way would be to provide 4 entry fields:
- 1 for all included directories
- 1 for all excluded directories
- 1 for all included files
- 1 for all excluded files

The listing of multiple items in each of the entry fields should be the same.

Current problems:
- The current entry fields for Excluded dirs and files names are much too short.
- Does (RegExp) after "Excluded dirs" means that items in other entry fields are not in RegExp format? Why?
- Does "|" as delimiter for only File Names match entry field mean that this is not an delimiter for excluded dirs?
- How can I specify multiple directories for search? How do I append them? With |" too?
- Mixing specifications for including and excluding file names in 1 entry field but not for including and excluding directories is unlogic.

I suggest to setup a more user friendly in+exclude dir+file specifiation

Thank you

**Comment by stefankueng** [comment]
- four entry fields is too much, there's not enough space for that
- the entry fields can scroll, so the width should suffice
- there's no delimiter for excluded dirs, because you have to specify a regex there
- the include files string can be a regex or a simple glob like most users are familiar with (e.g. *.cpp), when used like that the delimiter '|' can be used to specify multiple filemasks
- to search multiple directories, enter the paths in the "search in" box at the very top of the dialog, also with the '|' delimiter

**Comment by elig0n** [comment]
> * to search multiple directories, enter the paths in the "search in" box at the very top of the dialog, also with the '|' delimiter

I was looking for this feature and ended up searching the github issues. do you think you maybe can add it to the documentation / help or a tooltip or something similar ? Because it otherwise looks missing (I almost gave up)
