### ISSUE TITLE
Search does not obey Text/Regexp on $ character

### ISSUE THREAD

**Issue by StefanoBettega** [stefankueng/grepWin#261]
If you search a string, without regular expression, but containing the anchor character $, no results are found.

![image](https://user-images.githubusercontent.com/21540861/120149657-535c5480-c1ea-11eb-9f61-0f93222ba3d6.png)

If you remove the $, search works as expected.

![image](https://user-images.githubusercontent.com/21540861/120149699-5f481680-c1ea-11eb-8867-4d2546e49007.png)

**Comment by StefanoBettega** [comment]
I forgot to say that version is 2.0.8.1054, but this behavior was already present in preceding versions.

**Comment by stefankueng** [comment]
works fine for me.
But have a closer look at your own screenshots:
the results for when you search for `(PlatformToolset)` show that there is no `$(PlatformToolset)` in the files.
Only `$\(PlatformToolset)` - notice the backslash after the `$`. That's why you don't find it with your first search string but only with the one without the `$`

**Comment by StefanoBettega** [comment]
Ouch! I must change my glasses, or better change that damn scripting language.
Sorry for the wrong issue and thanks again!
