### ISSUE TITLE
Using ripgrep as underlying text searching lib

### ISSUE THREAD

**Issue by codec-abc** [stefankueng/grepWin#340]
Hi,

I am a long time user of grepWin that I like very much. I use it daily to parse find GUID in a bunch of yaml files (because doing Unity 3D stuff). The things is that as my Unity projects grow the search take longer. Of course it is expected but I think performance can be better. Searching the same string with grepWin and ripGrep with the same file pattern give me roughly an order of magnitude faster results for ripGrep over GrepWin. So I guess using ripGrep as an underlying library could improve performance quite a lot.

**Comment by stefankueng** [comment]
ripGrep is faster only because it omits a lot of what regex can do.

- it searches lines, so if your regex spans multiple lines, you're out of luck
- it does not support back references

for the first item, you can uncheck "dot matches newline", which makes grepWin also a little bit faster, but it still searches documents, not lines.
as for the second, well, grepWin is a regex search tool, not some "only some regex" search tool.
