### ISSUE TITLE
Upating the search/replace text fields during a replacement is taken into account

### ISSUE THREAD

**Issue by chacha21** [stefankueng/grepWin#426]
After launching a search/replace operation (that can take some time), I want to "prepare" the next search/replace by changing the content of the search/replace text fields.
But currently, updating the search/replace text fields during a search/replace operation is taken into account immediately in the currently executing search/replace operation.
It is unexpected and in my case undesirable.

**Comment by stefankueng** [comment]
I don't think this is really what happens. Because all search data (search and replace strings, settings like date range, search path, file flags to search, ...) are read from the UI when you click the search button and stored.
While the search/replace is going on, you can change the UI values as you like, but they're NOT taken into account immediately. If it is for you, you have to provide much more info on how you get it to do that.

**Comment by chacha21** [comment]
I can't reproduce what I have observed previously.
I will reopen if I can exhibit it again
