### ISSUE TITLE
Double clicking a file causes program to crash

### ISSUE THREAD

**Issue by smelcher** [stefankueng/grepWin#483]
When I double click on one of the files in the "Search results" tab, it causes GrepWin to crash out.  This behavior started with the release from a few weeks ago.  
Thanks!

**Comment by stefankueng** [comment]
I can not reproduce this.
What kind of files are shown/do you double click on? (txt, ...)
what default editor is configured for that file type?
does it happen for all files or just a few?

**Comment by smelcher** [comment]
I have tried a few different file types with the same behavior: .txt, .rar, .xls.  It seems to be happening for me for all file types.
My default editor for .txt files is Notepad++.

**Comment by craigtp** [comment]
I have the same problem, which I've noticed with .pdf and .epub files (if may affect other files, but these are the ones I've noticed the error with).  For both filetypes, my default program to open these files is [SumatraPDF](https://www.sumatrapdfreader.org/free-pdf-reader).

This issue was introduced in version 2.1.0.  The immediately prior version, 2.0.15 does not exhibit this behaviour.

**Comment by ask9** [comment]
@smelcher use old version. it is more stable and doesn't get crashed.
Starting with 2.1.0 it becomes nearly impossible to work with the app due to regular crashes.

**Comment by stefankueng** [comment]
I can reproduce the problem now: it only happens if there are no results in the found files (e.g. if you leave the search text empty and only search for filenames/types).
