### ISSUE TITLE
Regex Find imputs must be the same as Text Search inputs

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#508]
Input not highlight on **Regex Search**. The problem is that I cannot copy-paste many lines on Replace input, because is not like simple replace, is just one line. In the example below, the Search Input will consider online the first line `<ul class="sidebar-menu">`, if I try to copy all replacement lines. So, **the Regex Find imputs must be the same as Text Search inputs, otherwise it's hard to tell if all the text was copied, or what exactly was copied.**

**FIND:**  `<ul class="sidebar-menu">[\s\S]*?<!-- AM SCOS`

**REPLACE:**

```
<ul class="sidebar-menu"> 
  						<li>
                            <a href="https://neculaifantanaru.com/index.html">
                                <span>HOME</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://neculaifantanaru.com/carti-leadership.html">
                                <span>Carti</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://neculaifantanaru.com/feedback.html">
                                <span>FEED-BACK</span>
                            </a>
                        </li>
						<li>
                            <a href="https://neculaifantanaru.com/despre.html">
                                <span>Despre Mine</span>
                            </a>
                        </li>
						<li>
                            <a href="https://neculaifantanaru.com/contact.html">
                                <span>Contact</span>
                            </a>
                        </li> 

                    </ul>
                </nav>
<!-- AM SCOS
```

See print screens

![image](https://github.com/user-attachments/assets/5f0b250f-c5c3-4f37-b434-0cf3483b87c4)

**Comment by lifenjoiner** [comment]
Thanks for your feedback.

As you realized: **`Regex search` inputs must be kept as-is**.
Multi-line inputs are disabled for `Regex search`, because of Windows multi-line input box only yields `\r\n` results.
So, we made it stricter: users should use explicit line-encodings (`\r`, `\n` or `\r\n`). We do not modify your inputs any more, to make them cover all line-encodings.

In the short term, it's a little inconvenient, but in the long term, it will turn you into a regular expression master. As the expressions you write are getting more and more accurate.
