### ISSUE TITLE
keep existing "last modified date"

### ISSUE THREAD

**Issue by 4evermaat** [stefankueng/grepWin#51]
Can we have an option to retain the old "last modified date" in a file?  Multi file search/replace is good but I don't always want to change the "last modified date".  

There are other programs that can make changes to text-based files and retain the last modified date that is shown in windows explorer.  (I assume they save the old last modified date and after writing to the file overwrite the last modified date to the old date)

**Comment by terra111** [comment]
grepWin is so useful, I need it several times a month. Thanks a lot!

The only thing I miss, just like user @4evermaat , is the possibility to keep the file date. I always have to make mass changes to TXT files (just on eight hundred .lnk files [=web favorites] the paths to the icons have to be removed, because they contain the username(!), a privacy problem! 
Of course **it makes sense that the file keeps its old modification date**, because you want to know WHEN you created the favorite. And maybe you want to sort the favorites by modification date!

You are the developer of another useful tool, which keeps the file date when a file is changed: **SKTimeStamp**
**_Workflow:_** when making changes to a single file, I take SKTimeStamp and click through to the time change tab. Then I make the actual file change and save the file. Now it has the new file date. To get the previous one back, I now click on the time change tab that came from SKTimeStamp and click OK. Et voila! But very cumbersome.

A way to keep the file date in grepWin (via switch) would be I think for many users, very helpful!

**Comment by Coldblackice** [comment]
Great feature! Will use this often, thanks.

**Comment by 4evermaat** [comment]
Is it a switch/option?

**Comment by stefankueng** [comment]
![image](https://user-images.githubusercontent.com/665591/211846527-c04b9f04-d599-4856-b050-7aa785af8db9.png)

or on the command line `/keepfiledate=yes`
