### ISSUE TITLE
Why can't I add multiple lines one below the other in the Replace Regex input?

### ISSUE THREAD

**Issue by me-suzy** [stefankueng/grepWin#522]
Let's say I have this:

**FIND:** `<!--INCEPUT Stuctura MENIU-->([\s\S]*?)<!--FINAL Stuctura MENIU-->`

**Replace by:**

```
<!--INCEPUT Stuctura MENIU-->
Text 1-ro
Text 2-ro
Text 3-ro
<!--FINAL Stuctura MENIU-->
```

As seen in the image, only the first of the 5 lines can be entered in the Replace input: `<!--INCEPUT Stuctura MENIU-->`
I tested it, of course, and the replacement was done with only the first line. The other 4 were ignored.

![image](https://github.com/user-attachments/assets/2a2848d7-c018-444a-8f98-78b77888daad)

**Comment by lifenjoiner** [comment]
1. We don't know which line-encodings you are using: `\n`, `\r\n` or `\r`.
2. Windows multi-line box only yields `\r\n` result.

When in Regex mode, you can specify them, and should do it explicitly, unlike in text mode.

**Comment by me-suzy** [comment]
`When in Regex mode, you can specify them, and should do it explicitly, unlike in text mode.`

For beginners, or for the uninitiated, this would have been an easy way. You should have a checkbox if you want to not use regex for Replace. 

Instead of GrepWin, I use TextCrawler for this task. Works perfectly.

![image](https://github.com/user-attachments/assets/bb6fb177-18e7-4b05-8012-74834cd51c0f)

**Comment by lifenjoiner** [comment]
Hope everyone to learn to become an expert.

Although it is not encouraged due to the implicit line-encodings are invisible, if you want to input multi-line badly, there are still 2 ways:
1. You can input it in text mode first, and then switch to Regex mode.
2. And you can see, after you close the multi-line input box, the `\r\n` will look like a space char, which is hard to distinguish, especially when they are in the history tip list.
So, another solution I recommend is using the `Test regex` to generate a one line input with regex form line-encodings. `\r\n` to "\r\n" for example.

Using explicit line-encodings, you won't produce inconsistent line-encoding files, especially for *nix (cross platform) files, golang files and etc.

**Comment by me-suzy** [comment]
to replace also with regex, is a good solution. But if you have more text, more punctuation, more lines, diferent spaces, well, can take a lot of time, and mistakes...

So, for replace, will be better to put text directly, without regex. Save a lot of time, save a lot of mistakes. Textarea is better then input, for replace.

As I say before, a checkbox will be nice. Each person will consider if to copy text identicaly, or to use regex.
