### ISSUE TITLE
Suggestion: Add support for searching for binary data

### ISSUE THREAD

**Issue by mariomadproductions** [stefankueng/grepWin#53]
Suggestion: Add support for searching for binary data
E.g. in the form of hex values
An option to search for whole files within other files would also be useful.

**Comment by ghost** [comment]
LMAO right this moment I was about to open the same exact feature request, I need to grep alot of game folders for empty files, NUL NUL NUL ... because I accidentially ran DD and corrupted quite a lot of various small files such as .DLL and .EXE which pretty much ruined a lot of old non-steam games, chkdsk was able to repair the filesystem, retain filenames, the directory structure, but the data's gone.

Greping would find all those who are fully NUL, from top to bottom, but such an option should be specifically provided for this purpse because pasting a ton of NUL chars in the text box isn't very reliable, even valid DLL/EXE files use a lot of NUL space too in between, so it finds a lot of false positives.

**Comment by stefankueng** [comment]
use the proper regex:
\x{0}
to search for a null character.
or put any other value in the {} you want to search for.

**Comment by mariomadproductions** [comment]
Would that allow me to search for binary data too?

**Comment by stefankueng** [comment]
yes: just put the byte value in the brackets.

**Comment by ghost** [comment]
Allright, That should cover many cases but still then "add support for empty file detection", which would match any file without any or with just NUL chars. Because it's still unpractical to put many kilobytes worth of zeroes into the brackets.
