### ISSUE TITLE
Feature Request: Search with sorting

### ISSUE THREAD

**Issue by imsmart-tech** [stefankueng/grepWin#82]
What I find would be very interesting is:
- While searching through a directory, to be able to sort which files are searched first. For example, I'd like to find the earliest file that contains a give string. Since the folder is very big I can then stop the search as soon as I see a few files found.

So you could have sort by: Name (ASC/DESC), Date Modified (ASC/DESC), Date Created (ASC/DESC), Size (ASC/DESC).

Thank you.

**Comment by stefankueng** [comment]
Doing that would slow down searching a lot. That's why I'm not going to do that.
To do what you ask would mean to first fetch the list of all files and only then start searching the file contents. But listing all files can also take a lot of time - you can see that effect when you copy a big folder with explorer: the progress dialog won't show proper progress for a few seconds. Only after it has all the files listed it will show that progress.
Now try that with really big folders and you'll see that those 'few seconds' can sometimes take a minute or even more.
